# Max number of threads to run job
threads_max: 20
# Max memory to run job
memory_max: 188416
# Min memory to run job. Should be equatl to at least memory_max/threads_max
memory_min: 8192
# tmp directory
tmp_dir: "/tmp"

# Main directory of the project where other directories are located
project_dir: "/data"
# Directory with specific sample data
samples_dir: "samples"
# Directory with reads
reads_dir: "reads"
# Directory with genomic data
genome_dir: "genome"
# Directory with chromosomes sequences
genome_chrom_dir: "Chromosomes"
# Genome prefix
genome_prefix: "CanFam3.1.Ensembl.94"
variants_dir: "variants"
result_cnv_dir: "results_cnvs"

bait_intervals: "bait_intervals"
target_intervals: "target_intervals"

heterosomes_ploidy: "/data/heterosomes_ploidy.tsv"

gatk:
  autosomes_ploidy: 2
  heterosomes: ["X", ]
  max_reads: 100
  report_num_alleles: "true"
  max_num_alleles: 16
  all_site_pls: "true"
  max_assembly_size: 500
  assembly_padding: 150
  annotation_groups: ["AS_StandardAnnotation", "ReducibleAnnotation"]
  annotations: [
    "BaseQualityRankSumTest",
    "AS_BaseQualityRankSumTest",
    "FisherStrand",
    "AS_FisherStrand",
    "MappingQualityRankSumTest",
    "AS_MappingQualityRankSumTest",
    "RMSMappingQuality",
    "AS_RMSMappingQuality",
    "QualByDepth",
    "AS_QualByDepth",
    "StrandOddsRatio",
    "AS_StrandOddsRatio",
    "ReadPosRankSumTest",
    "AS_ReadPosRankSumTest",
    "ChromosomeCounts",
    "ClippingRankSumTest",
    "Coverage",
    "DepthPerAlleleBySample",
    "DepthPerSampleHC",
    "LikelihoodRankSumTest",
    "MappingQualityZero",
    "SampleList",
    "TandemRepeat",
  ]

snpeff:
  database: "/SnpEff"

cnvnator:
  bin_size: 500

delly:
  sv_types: ["DEL", "INS", "DUP", "INV", "BND"]
  #sv_types: ["DEL", "INS", "DUP", "INV"]

cnmops:
  script_standard: "/ngsnake/cnmops.R"
  script_cvsc: "/ngsnake/cnmops_cvsc.R"
  groups_file: "/data/cnmops_groups.tsv"
  segAlgorithm: "DNAcopy"
  WL: 100
  returnPosterior: true
