# Max number of threads to run job
threads_max: 20
# Max memory to run job
memory_max: 188416
# tmp directory
tmp_dir: "/tmp"

project_dir: "/data"
samples_dir: "samples"
reads_dir: "reads"
genome_dir: "genome"
genome_prefix: "CanFam3.1.Ensembl.94"
variants_dir: "variants"

bait_intervals: "bait_intervals"
target_intervals: "target_intervals"

gatk_autosomes_ploidy: 2
gatk_heterosomes: ["X", ]
gatk_heterosomes_ploidy: "/data/heterosomes_ploidy.tsv"
gatk_max_reads: 100
gatk_report_num_alleles: "true"
gatk_max_num_alleles: 16
gatk_all_site_pls: "true"
gatk_max_assembly_size: 500
gatk_assembly_padding: 150
gatk_annotation_groups: ["AS_StandardAnnotation", "ReducibleAnnotation"]
gatk_annotations: [
  "BaseQualityRankSumTest",
  "AS_BaseQualityRankSumTest",
  "FisherStrand",
  "AS_FisherStrand",
  "MappingQualityRankSumTest",
  "AS_MappingQualityRankSumTest",
  "RMSMappingQuality",
  "AS_RMSMappingQuality",
  "QualByDepth",
  "AS_QualByDepth",
  "StrandOddsRatio",
  "AS_StrandOddsRatio",
  "ReadPosRankSumTest",
  "AS_ReadPosRankSumTest",
  "ChromosomeCounts",
  "ClippingRankSumTest",
  "Coverage",
  "DepthPerAlleleBySample",
  "DepthPerSampleHC",
  "LikelihoodRankSumTest",
  "MappingQualityZero",
  "SampleList",
  "TandemRepeat",
]

snpeff_database: "/SnpEff"
